clear all; close all;

launcher_dir = fileparts(mfilename('fullpath'));

fig = uifigure('Name', 'Design of Visual Systems', ...
               'Position', [400 400 560 340]);

% Title
uilabel(fig, 'Text', 'Visual Systems Project', ...
             'Position', [80 280 400 35], ...
             'FontSize', 20, 'FontWeight', 'bold', ...
             'HorizontalAlignment', 'center');

% Subtitle
uilabel(fig, 'Text', 'A visual toolkit to measure and style your photographs.', ...
             'Position', [80 245 400 30], ...
             'FontSize', 16, ...
             'FontColor', [0.4 0.4 0.4], ...
             'HorizontalAlignment', 'center');

% Button: Object Size
uibutton(fig, 'push', ...
              'Text', 'Object Size Measurement', ...
              'Position', [40 160 200 55], ...
              'FontSize', 14, ...
              'ButtonPushedFcn', @(btn,event) launch('object-size-final/main.m', launcher_dir));

uilabel(fig, 'Text', 'Requires a clear photograph with your object and a credit card.', ...
             'Position', [20 110 240 45], ...
             'FontSize', 12, ...
             'FontColor', [0.5 0.5 0.5], ...
             'WordWrap', 'on', ...
             'HorizontalAlignment', 'center');

% Button: Artify
uibutton(fig, 'push', ...
              'Text', 'Artify Photographs', ...
              'Position', [320 160 200 55], ...
              'FontSize', 14, ...
              'ButtonPushedFcn', @(btn,event) launch('artify/DVS_project.m', launcher_dir));

uilabel(fig, 'Text', 'Any photograph you would like to style.', ...
             'Position', [300 110 240 45], ...
             'FontSize', 12, ...
             'FontColor', [0.5 0.5 0.5], ...
             'WordWrap', 'on', ...
             'HorizontalAlignment', 'center');


function launch(filepath, launcher_dir)
    % Set default to current folder
    cd(launcher_dir);

    % Launch the challenge folder
    [folder, name, ~] = fileparts(filepath);
    cd(folder);
    run(name);
end